// Generated by gencpp from file ar_tag/ImageSrv.msg
// DO NOT EDIT!


#ifndef AR_TAG_MESSAGE_IMAGESRV_H
#define AR_TAG_MESSAGE_IMAGESRV_H

#include <ros/service_traits.h>


#include <ar_tag/ImageSrvRequest.h>
#include <ar_tag/ImageSrvResponse.h>


namespace ar_tag
{

struct ImageSrv
{

typedef ImageSrvRequest Request;
typedef ImageSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageSrv
} // namespace ar_tag


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ar_tag::ImageSrv > {
  static const char* value()
  {
    return "ba55116f263d40ea8759822097ad63d4";
  }

  static const char* value(const ::ar_tag::ImageSrv&) { return value(); }
};

template<>
struct DataType< ::ar_tag::ImageSrv > {
  static const char* value()
  {
    return "ar_tag/ImageSrv";
  }

  static const char* value(const ::ar_tag::ImageSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ar_tag::ImageSrvRequest> should match 
// service_traits::MD5Sum< ::ar_tag::ImageSrv > 
template<>
struct MD5Sum< ::ar_tag::ImageSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ar_tag::ImageSrv >::value();
  }
  static const char* value(const ::ar_tag::ImageSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ar_tag::ImageSrvRequest> should match 
// service_traits::DataType< ::ar_tag::ImageSrv > 
template<>
struct DataType< ::ar_tag::ImageSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ar_tag::ImageSrv >::value();
  }
  static const char* value(const ::ar_tag::ImageSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ar_tag::ImageSrvResponse> should match 
// service_traits::MD5Sum< ::ar_tag::ImageSrv > 
template<>
struct MD5Sum< ::ar_tag::ImageSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ar_tag::ImageSrv >::value();
  }
  static const char* value(const ::ar_tag::ImageSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ar_tag::ImageSrvResponse> should match 
// service_traits::DataType< ::ar_tag::ImageSrv > 
template<>
struct DataType< ::ar_tag::ImageSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ar_tag::ImageSrv >::value();
  }
  static const char* value(const ::ar_tag::ImageSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AR_TAG_MESSAGE_IMAGESRV_H
